# Generated by Django 4.2.4 on 2024-12-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_updated_date_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_date',
            new_name='published',
        ),
    ]
