# Generated by Django 4.2.4 on 2025-01-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_main_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='main_doctor',
            new_name='family_doctor',
        ),
    ]
